name: Deploy Infrastructure

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: ['main']
    paths:
      - 'infrastructure/**'
      # - ".github/workflows/**"

env:
  REPO_NAME: ${{ github.repository }}

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.AWS_DEPLOY_CDK_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
          role-session-name: 'GitHubActions-DeployCdkStacks'

      - name: Deploy CDK Stacks
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_args: '--require-approval never'
          actions_comment: false
          working_dir: './infrastructure'
